SETTING_PARAMS = {
    'Apache': {
        'input_dir': '../../logs2k/Apache/',
        'log_file': 'Apache_2k.log',
        'log_template': 'Apache_2k.log_templates.csv',
        'log_structure': 'Apache_2k.log_structured_corrected.csv',
        'log_format': '\[<Time>\] \[<Level>\] <Content>',
        'token_regexs': [
            [r'\/(?:\w+\/){2,}\w+\.\w+$', "<*>"],
            [r'\/(?:[^\/\s]+\/)*[^\/\s]*', "<*>"],
            [r'(?:[0-9a-fA-F]{2,}:){3,}[0-9a-fA-F]{2,}', "<*>"],
        ],   
        'n_merge': 3,
        'st':0.6,
        'merge_special': True,  
        'punctuationL': "()\{\}[]=:,@",
        'special_tokens': [
            'true', 'false', 'null', 'root'
        ],
    },
    'BGL': {
        'input_dir': '../../logs2k/BGL/',
        'log_file': 'BGL_2k.log',
        'log_template': 'BGL_2k.log_templates_corrected.csv',
        'log_structure': 'BGL_2k.log_structured_corrected.csv',
        'log_format': '<Label> <Timestamp> <Date> <Node> <Time> <NodeRepeat> <Type> <Component> <Level> <Content>',
        'token_regexs': [
            [r"core\.\d+", "core.<*>"],
            [r'(?:[0-9a-fA-F]{2,}:){3,}[0-9a-fA-F]{2,}', "<*>"],
            [r'(\.{2,})\d+', r'\1<*>'],
        ],  
        'n_merge': 4,
        'st':0.7,
        'merge_special': False,  
        'punctuationL': "[]<>()\{\}=:,@",
        'special_tokens': ['true', 'false', 'null', 'root'],  
    },
    'Hadoop': {
        'input_dir': '../../logs2k/Hadoop/',
        'log_file': 'Hadoop_2k.log',
        'log_template': 'Hadoop_2k.log_templates.csv',
        'log_structure': 'Hadoop_2k.log_structured_corrected.csv',
        'log_format': '<Date> <Time> <Level> \[<Process>\] <Component>: <Content>',
        'token_regexs': [
            # [r'\[.*?(_.*?)+\]', "<*>"],
            [ r'^(?:[\\\/]?[^\\\/]+[\\\/]){2,}[^\\\/]+\.\w+(?=\s|$)', "<*>"],
        ],   
        'n_merge': 3,
        'st':0.6,
        'merge_special': False,  
        'punctuationL': '[]<>(){}=:,@#/',
        'special_tokens': ['true', 'false', 'null', 'root'], 
    },
    'HDFS': {
        'input_dir': '../../logs2k/HDFS/',
        'log_file': 'HDFS_2k.log',
        'log_template': 'HDFS_2k.log_templates.csv',
        'log_structure': 'HDFS_2k.log_structured_corrected.csv',
        'log_format': '<Date> <Time> <Pid> <Level> <Component>: <Content>',
        'token_regexs': [
        ],    
        'n_merge': 3,
        'st':0.6,
        'merge_special': False,  
        'punctuationL': '[]<>(){}=:,@#',
        'special_tokens': ['true', 'false', 'null', 'root'], 
    },
    'HealthApp': {
        'input_dir': '../../logs2k/HealthApp/',
        'log_file': 'HealthApp_2k.log',
        'log_template': 'HealthApp_2k.log_templates.csv',
        'log_structure': 'HealthApp_2k.log_structured_corrected.csv',
        'log_format': '<Time>\|<Component>\|<Pid>\|<Content>',
        'token_regexs': [
            
        ],  
        'n_merge': 4,
        'st':0.6,
        'merge_special': False,  
        'punctuationL': '[]<>(){}=:,#',
        'special_tokens': ['true', 'false', 'null', 'root'], 
    },
    'HPC':{
        'input_dir': '../../logs2k/HPC/',
        'log_file': 'HPC_2k.log',
        'log_template': 'HPC_2k.log_templates.csv',
        'log_structure': 'HPC_2k.log_structured_corrected.csv',
        'log_format': '<LogId> <Node> <Component> <State> <Time> <Flag> <Content>',
        'token_regexs': [
            [r'node-\d+(?=$|\s)', "node-<*>"],
        ],  
        'n_merge': 3,
        'st':0.7,
        'merge_special': False,  
        'punctuationL': '[](){}=:',
        'special_tokens': ['true', 'false', 'null', 'root'], 
    },
    'Linux': {
        'input_dir': '../../logs2k/Linux/',
        'log_file': 'Linux_2k.log',
        'log_template': 'Linux_2k.log_templates.csv',
        'log_structure': 'Linux_2k.log_structured_rev.csv',
        'log_format': '<Month> <Date> <Time> <Level> <Component>(\[<PID>\])?: <Content>',
        'token_regexs': [
            [r'(\d+\.){3}\d+', "<*>"],
            [r'\d{2,}:\d{2,}:\d{2,}', "<*>"],
        ],  
        'n_merge': 30,
        'st':0.6,
        'merge_special': False,  
        'punctuationL': '[](){}=:#,',
        'special_tokens': [
            'true', 'false', 'null', 'root', 
            'Mon', 'Tue', 'Wed', 'Thu', "Fri", 'Sat', 'Sun',
            "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
        ], 
    },
    'Proxifier': {
        'input_dir': '../../logs2k/Proxifier/',
        'log_file': 'Proxifier_2k.log',
        'log_template': 'Proxifier_2k.log_templates.csv',
        'log_structure': 'Proxifier_2k.log_structured_rev.csv',
        'log_format': '\[<Time>\] <Program> - <Content>',
        'token_regexs': [
            [r'<\d+\ssec', "<*>"],
            [r'\(\d+(?:.\d+) [KGTM]B\)', "(<*>)"], 
            [r'(?:\b|^)[\w.-]+\.cuhk\.edu\.hk', "<*>"],
        ],
        'n_merge': 3,
        'st':0.7,
        'merge_special': False,  
        'punctuationL': '[](){}=:',
        'special_tokens': ['true', 'false', 'null', 'root'], 
    },
    'Mac': {
        'input_dir': '../../logs2k/Mac/',
        'log_file': 'Mac_2k.log',
        'log_template': 'Mac_2k.log_templates.csv',
        'log_structure': 'Mac_2k.log_structured_rev.csv',
        'log_format': '<Month>  <Date> <Time> <User> <Component>\[<PID>\]( \(<Address>\))?: <Content>',
        'token_regexs': [
            ['(?:[0-9a-fA-F]{2}:){3,}[0-9a-fA-F]{2}', "<*>"],
            [r'([\\\/]([\w.-@#!]+?)){2,}[\\\/]([\w.-@#!]+)', "<*>"],
            [r'\d{4}-\d{1,2}-\d{1,2}', '<*>-<*>-<*>'],
            [r'\d{4}\/\d{1,2}\/\d{1,2}', '<*>/<*>/<*>'],
            [r'https?:\/\/(.+?)(?=\s|$|,|])', "<*>"],
        ],  
        'n_merge': 5,
        'st':0.7,
        'merge_special': False,  
        'punctuationL': "[](){}=:#,@",
        'special_tokens': [
            'true', 'false', 'null', 'root', 
        ], 
    },
    'OpenSSH': {
        'input_dir': '../../logs2k/OpenSSH/',
        'log_file': 'OpenSSH_2k.log',
        'log_template': 'OpenSSH_2k.log_templates.csv',
        'log_structure': 'OpenSSH_2k.log_structured_corrected.csv',
        'log_format': '<Date> <Day> <Time> <Component> sshd\[<Pid>\]: <Content>',
        'token_regexs': [
        ],  
        'n_merge': 5,
        'st':0.6,
        'merge_special': False,  
        'punctuationL': "[](){}=:#,@",
        'special_tokens': [
            'true', 'false', 'null', 'root', 
        ],  
    },
    'OpenStack': {
        'input_dir': '../../logs2k/OpenStack/',
        'log_file': 'OpenStack_2k.log',
        'log_template': 'OpenStack_2k.log_templates.csv',
        'log_structure': 'OpenStack_2k.log_structured_rev.csv',
        'log_format': '<Logrecord> <Date> <Time> <Pid> <Level> <Component> \[<ADDR>\] <Content>',
        'token_regexs': [
            [r'\d{4}-\d{1,2}-\d{1,2}', '<*>-<*>-<*>'],
            [r'\d{4}\/\d{1,2}\/\d{1,2}', '<*>/<*>/<*>'],
            [r'HTTP\/\d+\.\d+', "<*>"],
        ],   
        'n_merge': 5,
        'st':0.5,
        'merge_special': False,  
        'punctuationL': "[](){}=:,'",
        'special_tokens': [
            'true', 'false', 'null', 'root', 
        ],  
    },
    'Spark': {
        'input_dir': '../../logs2k/Spark/',
        'log_file': 'Spark_2k.log',
        'log_template': 'Spark_2k.log_templates.csv',
        'log_structure': 'Spark_2k.log_structured_corrected.csv',
        'log_format': '<Date> <Time> <Level> <Component>: <Content>',
        'token_regexs': [
            ["\d+(?:\.\d+)?\s?(?:[KM]?B)", "<*>"],
        ],    
        'n_merge': 6,
        'st':0.6,
        'merge_special': False,  
        'punctuationL': "[](){}=:,'",
        'special_tokens': [
            'true', 'false', 'null', 'root', 
        ],  
    },
    'Thunderbird': {
        'input_dir': '../../logs2k/Thunderbird/',
        'log_file': 'Thunderbird_2k.log',
        'log_template': 'Thunderbird_2k.log_templates.csv',
        'log_structure': 'Thunderbird_2k.log_structured_corrected.csv',
        'log_format': '<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Component>(\[<PID>\])?: <Content>',
        'token_regexs': [
            [r'(?:[0-9a-fA-F]{2}:){3,}[0-9a-fA-F]{2}', "<*>"],
            [r'(?:[\\\/][\w.\-@#!_]+){2,}', "<*>"]
        ],
        'n_merge': 3,
        'st':0.5,
        'merge_special': False,  
        'punctuationL': "[](){}=:,'#",
        'special_tokens': [
            'true', 'false', 'null', 'root', 
        ], 
    },
    'Zookeeper': {
        'input_dir': '../../logs2k/Zookeeper/',
        'log_file': 'Zookeeper_2k.log',
        'log_template': 'Zookeeper_2k.log_templates.csv',
        'log_structure': 'Zookeeper_2k.log_structured_corrected.csv',
        'log_format': '<Date> <Time> - <Level>  \[<Node>:<Component>@<Id>\] - <Content>',
        'filters': [],
        'token_regexs': [
        ], 
        'n_merge': 4,
        'st':0.7,
        'merge_special': False,  
        'punctuationL': "[](){}=:,@;#",
        'special_tokens': [
            'true', 'false', 'null', 'root', 
        ],    
    },
}

# SETTING_PARAMS = {
#     'Apache': {
#         'input_dir': '../../logs/Apache/',
#         'log_file': 'Apache_full.log',
#         'log_template': 'Apache_full.log_templates.csv',
#         'log_structure': 'Apache_full.log_structured.csv',
#         'log_format': '\[<Time>\] \[<Level>\] <Content>',
#         'token_regexs': [
#             [r'\/(?:\w+\/){2,}\w+\.\w+$', "<*>"],
#             [r'\/(?:[^\/\s]+\/)*[^\/\s]*', "<*>"],
#             [r'(?:[0-9a-fA-F]{2,}:){3,}[0-9a-fA-F]{2,}', "<*>"],
#         ],   
#         'n_merge': 3,
#         'st':0.6,
#         'merge_special': True,  
#         'punctuationL': "()\{\}[]=:,@",
#         'special_tokens': [
#             'true', 'false', 'null', 'root'
#         ],
#     },
#     'BGL': {
#         'input_dir': '../../logs/BGL/',
#         'log_file': 'BGL_full.log',
#         'log_template': 'BGL_full.log_templates.csv',
#         'log_structure': 'BGL_full.log_structured.csv',
#         'log_format': '<Label> <Timestamp> <Date> <Node> <Time> <NodeRepeat> <Type> <Component> <Level> <Content>',
#         'token_regexs': [
#             [r"core\.\d+", "core.<*>"],
#             [r'(?:[0-9a-fA-F]{2,}:){3,}[0-9a-fA-F]{2,}', "<*>"],
#             [r'(\.{2,})\d+', r'\1<*>'],
#         ],  
#         'n_merge': 4,
#         'st':0.7,
#         'merge_special': False,  
#         'punctuationL': "[]<>()\{\}=:,@",
#         'special_tokens': ['true', 'false', 'null', 'root'],  
#     },
#     'Hadoop': {
#         'input_dir': '../../logs/Hadoop/',
#         'log_file': 'Hadoop_full.log',
#         'log_template': 'Hadoop_full.log_templates.csv',
#         'log_structure': 'Hadoop_full.log_structured.csv',
#         'log_format': '<Date> <Time> <Level> \[<Process>\] <Component>: <Content>',
#         'token_regexs': [
#             # [r'\[.*?(_.*?)+\]', "<*>"],
#             [ r'^(?:[\\\/]?[^\\\/]+[\\\/]){2,}[^\\\/]+\.\w+(?=\s|$)', "<*>"],
#         ],   
#         'n_merge': 3,
#         'st':0.6,
#         'merge_special': False,  
#         'punctuationL': '[]<>(){}=:,@#/',
#         'special_tokens': ['true', 'false', 'null', 'root'], 
#     },
#     # 'HDFS': {
#     #     'input_dir': '../../logs/HDFS/',
#     #     'log_file': 'HDFS_full.log',
#     #     'log_template': 'HDFS_full.log_templates.csv',
#     #     'log_structure': 'HDFS_full.log_structured.csv',
#     #     'log_format': '<Date> <Time> <Pid> <Level> <Component>: <Content>',
#     #     'token_regexs': [
#     #     ],    
#     #     'n_merge': 3,
#     #     'st':0.6,
#     #     'merge_special': False,  
#     #     'punctuationL': '[]<>(){}=:,@#',
#     #     'special_tokens': ['true', 'false', 'null', 'root'], 
#     # },
#     'HealthApp': {
#         'input_dir': '../../logs/HealthApp/',
#         'log_file': 'HealthApp_full.log',
#         'log_template': 'HealthApp_full.log_templates.csv',
#         'log_structure': 'HealthApp_full.log_structured.csv',
#         'log_format': '<Time>\|<Component>\|<Pid>\|<Content>',
#         'token_regexs': [
            
#         ],  
#         'n_merge': 4,
#         'st':0.6,
#         'merge_special': False,  
#         'punctuationL': '[]<>(){}=:,#',
#         'special_tokens': ['true', 'false', 'null', 'root'], 
#     },
#     'HPC':{
#         'input_dir': '../../logs/HPC/',
#         'log_file': 'HPC_full.log',
#         'log_template': 'HPC_full.log_templates.csv',
#         'log_structure': 'HPC_full.log_structured.csv',
#         'log_format': '<LogId> <Node> <Component> <State> <Time> <Flag> <Content>',
#         'token_regexs': [
#             [r'node-\d+(?=$|\s)', "node-<*>"],
#         ],  
#         'n_merge': 3,
#         'st':0.7,
#         'merge_special': False,  
#         'punctuationL': '[](){}=:',
#         'special_tokens': ['true', 'false', 'null', 'root'], 
#     },
#     'Linux': {
#         'input_dir': '../../logs/Linux/',
#         'log_file': 'Linux_full.log',
#         'log_template': 'Linux_full.log_templates.csv',
#         'log_structure': 'Linux_full.log_structured.csv',
#         'log_format': '<Month> <Date> <Time> <Level> <Component>(\[<PID>\])?: <Content>',
#         'token_regexs': [
#             [r'(\d+\.){3}\d+', "<*>"],
#             [r'\d{2,}:\d{2,}:\d{2,}', "<*>"],
#         ],  
#         'n_merge': 30,
#         'st':0.6,
#         'merge_special': False,  
#         'punctuationL': '[](){}=:#,',
#         'special_tokens': [
#             'true', 'false', 'null', 'root', 
#             'Mon', 'Tue', 'Wed', 'Thu', "Fri", 'Sat', 'Sun',
#             "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
#         ], 
#     },
#     'Proxifier': {
#         'input_dir': '../../logs/Proxifier/',
#         'log_file': 'Proxifier_full.log',
#         'log_template': 'Proxifier_full.log_templates.csv',
#         'log_structure': 'Proxifier_full.log_structured.csv',
#         'log_format': '\[<Time>\] <Program> - <Content>',
#         'token_regexs': [
#             [r'<\d+\ssec', "<*>"],
#             [r'\(\d+(?:.\d+) [KGTM]B\)', "(<*>)"], 
#             [r'(?:\b|^)[\w.-]+\.cuhk\.edu\.hk', "<*>"],
#         ],
#         'n_merge': 3,
#         'st':0.7,
#         'merge_special': False,  
#         'punctuationL': '[](){}=',
#         'special_tokens': ['true', 'false', 'null', 'root'], 
#     },
#     'Mac': {
#         'input_dir': '../../logs/Mac/',
#         'log_file': 'Mac_full.log',
#         'log_template': 'Mac_full.log_templates.csv',
#         'log_structure': 'Mac_full.log_structured.csv',
#         'log_format': '<Month>  <Date> <Time> <User> <Component>\[<PID>\]( \(<Address>\))?: <Content>',
#         'token_regexs': [
#             ['(?:[0-9a-fA-F]{2}:){3,}[0-9a-fA-F]{2}', "<*>"],
#             [r'([\\\/]([\w.-@#!]+?)){2,}[\\\/]([\w.-@#!]+)', "<*>"],
#             [r'\d{4}-\d{1,2}-\d{1,2}', '<*>-<*>-<*>'],
#             [r'\d{4}\/\d{1,2}\/\d{1,2}', '<*>/<*>/<*>'],
#             [r'https?:\/\/(.+?)(?=\s|$|,|])', "<*>"],
#         ],  
#         'n_merge': 5,
#         'st':0.7,
#         'merge_special': False,  
#         'punctuationL': "[](){}=:#,@",
#         'special_tokens': [
#             'true', 'false', 'null', 'root', 
#         ], 
#     },
#     'OpenSSH': {
#         'input_dir': '../../logs/OpenSSH/',
#         'log_file': 'OpenSSH_full.log',
#         'log_template': 'OpenSSH_full.log_templates.csv',
#         'log_structure': 'OpenSSH_full.log_structured.csv',
#         'log_format': '<Date> <Day> <Time> <Component> sshd\[<Pid>\]: <Content>',
#         'token_regexs': [
#         ],  
#         'n_merge': 5,
#         'st':0.6,
#         'merge_special': False,  
#         'punctuationL': "[](){}=:#,@",
#         'special_tokens': [
#             'true', 'false', 'null', 'root', 
#         ],  
#     },
#     'OpenStack': {
#         'input_dir': '../../logs/OpenStack/',
#         'log_file': 'OpenStack_full.log',
#         'log_template': 'OpenStack_full.log_templates.csv',
#         'log_structure': 'OpenStack_full.log_structured.csv',
#         'log_format': '<Logrecord> <Date> <Time> <Pid> <Level> <Component> \[<ADDR>\] <Content>',
#         'token_regexs': [
#             [r'\d{4}-\d{1,2}-\d{1,2}', '<*>-<*>-<*>'],
#             [r'\d{4}\/\d{1,2}\/\d{1,2}', '<*>/<*>/<*>'],
#             [r'HTTP\/\d+\.\d+', "<*>"],
#         ],   
#         'n_merge': 5,
#         'st':0.5,
#         'merge_special': False,  
#         'punctuationL': "[](){}=:,'",
#         'special_tokens': [
#             'true', 'false', 'null', 'root', 
#         ],  
#     },
#     # 'Spark': {
#     #     'input_dir': '../../logs/Spark/',
#     #     'log_file': 'Spark_full.log',
#     #     'log_template': 'Spark_full.log_templates.csv',
#     #     'log_structure': 'Spark_full.log_structured.csv',
#     #     'log_format': '<Date> <Time> <Level> <Component>: <Content>',
#     #     'token_regexs': [
#     #         ["\d+(?:\.\d+)?\s?(?:[KM]?B)", "<*>"],
#     #     ],    
#     #     'n_merge': 6,
#     #     'st':0.6,
#     #     'merge_special': False,  
#     #     'punctuationL': "[](){}=:,'",
#     #     'special_tokens': [
#     #         'true', 'false', 'null', 'root', 
#     #     ],  
#     # },
#     # 'Thunderbird': {
#     #     'input_dir': '../../logs/Thunderbird/',
#     #     'log_file': 'Thunderbird_full.log',
#     #     'log_template': 'Thunderbird_full.log_templates.csv',
#     #     'log_structure': 'Thunderbird_full.log_structured.csv',
#     #     'log_format': '<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Component>(\[<PID>\])?: <Content>',
#     #     'token_regexs': [
#     #         [r'(?:[0-9a-fA-F]{2}:){3,}[0-9a-fA-F]{2}', "<*>"],
#     #         [r'(?:[\\\/][\w.\-@#!_]+){2,}', "<*>"]
#     #     ],
#     #     'n_merge': 3,
#     #     'st':0.5,
#     #     'merge_special': False,  
#     #     'punctuationL': "[](){}=:,'#",
#     #     'special_tokens': [
#     #         'true', 'false', 'null', 'root', 
#     #     ], 
#     # },
#     'Zookeeper': {
#         'input_dir': '../../logs/Zookeeper/',
#         'log_file': 'Zookeeper_full.log',
#         'log_template': 'Zookeeper_full.log_templates.csv',
#         'log_structure': 'Zookeeper_full.log_structured.csv',
#         'log_format': '<Date> <Time> - <Level>  \[<Node>:<Component>@<Id>\] - <Content>',
#         'filters': [],
#         'token_regexs': [
#         ], 
#         'n_merge': 4,
#         'st':0.7,
#         'merge_special': False,  
#         'punctuationL': "[](){}=:,@;#",
#         'special_tokens': [
#             'true', 'false', 'null', 'root', 
#         ],    
#     },
# }